spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hs-spring-db.cjhazvr1oeo5.ap-northeast-2.rds.amazonaws.com:3306/weatherfit
    username: wlfkrdl2
    password: gmltjd36!
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    prefer-ip-address: true
    ip-address: 3.35.59.210
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://13.124.197.227:8761/eureka
server:
  port: 8080

